# Generated by Django 5.2.2 on 2025-06-09 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('po_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('Kg', 'Kilogram'), ('gm', 'Gram'), ('nos', 'Numbers'), ('dozen', 'Dozen'), ('pairs', 'Pairs'), ('ml', 'Milliliter'), ('ltr', 'Liter')], default='Kg', max_length=20),
        ),
    ]
