# Generated by Django 5.2.2 on 2025-06-09 09:01

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('po_system', '0002_alter_product_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='proposed_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional: Proposed price for this product', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='product',
            name='proposed_stock',
            field=models.IntegerField(blank=True, help_text='Optional: Proposed stock quantity', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(default='Kg', max_length=20),
        ),
    ]
