# Generated by Django 5.2.2 on 2025-06-11 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("po_system", "0003_alter_product_proposed_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorder",
            name="notes",
            field=models.TextField(
                blank=True, help_text="Additional notes or instructions", null=True
            ),
        ),
    ]
